name: Ephemeral Test Using Testkube
on:
  push:
    branches: [ "main" ]

jobs:
  testkube-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Kind Cluster
        uses: helm/kind-action@v1.9.0

      - name: Deploy Sample Application
        run: |
          kubectl apply -f nginx-deployment.yaml

      - name: Setup Testkube with Helm
        run: |
          helm repo add testkubeenterprise https://kubeshop.github.io/testkube-cloud-charts
      - name: Configure Testkube Agent
        run: |
          helm upgrade --install --reuse-values --create-namespace --namespace testkube testkube testkubeenterprise/testkube-enterprise \
            --set testkube-api.cloud.key=${{ secrets.TESTKUBE_API_TOKEN }} \
            --set testkube-api.cloud.orgId=${{ secrets.TESTKUBE_ORG_ID }} \
            --set testkube-api.cloud.envId=${{ secrets.TESTKUBE_ENV_ID }} \
            --set testkube-api.minio.enabled=false \
            --set mongodb.enabled=false \
            --set testkube-dashboard.enabled=false \
            --set testkube-api.cloud.url=agent.testkube.io:443

      - name: Check Testkube Version and Pods Status
        run: |
          echo "check testkube version sonali"
          testkube version
          kubectl get pods --all-namespaces -o wide
          POD_NAME=$(kubectl get pods -n testkube | grep testkube-api-server | awk '{print $1}')
          kubectl wait --for=condition=Ready pod/$POD_NAME -n testkube --timeout=200s

      - name: Run Testkube Test
        uses: kubeshop/setup-testkube@v1        
      - run: |
          testkube create testworkflow --name k6-kubeshop-test-file-remote -f k6/testkube.js --update    
          testkube run tw k6-kubeshop-test2 -f --variable "NGINX_URL=http://nginx-service.default.svc.cluster.local"
