name: Ephemeral Test Using Testkube
on:
  pull_request: 

jobs:
  testkube-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Run Testkube Test
        uses: kubeshop/setup-testkube@v1
        with:
          organization: ${{ secrets.TESTKUBE_ORG_ID }}
          environment: ${{ secrets.TESTKUBE_ENV_ID }}
          token: ${{ secrets.TESTKUBE_API_TOKEN }}

      - run: |
          testkube create testworkflow --name k6-test -f test-workflow.yaml   
          testkube run tw k6-test
